# adding cmake to system path
export PATH=${TRAVIS_BUILD_DIR}/${CMAKE_DIRNAME}:${TRAVIS_BUILD_DIR}/${CMAKE_DIRNAME}/bin:$PATH

mkdir build
cd build
cmake -DENABLE_FILESYSTEM=OFF -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DMVVM_GTEST_DISCOVER_TESTS=$TESTS_AUTODISCOVERY ..
make -j4
