export PATH=/usr/local/opt/qt5/bin/:$PATH
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DMVVM_TESTS_AUTOEXEC=$TESTS_AUTOEXEC -DMVVM_TESTS_AUTODISCOVERY=$TESTS_AUTODISCOVRY ..
make -j4
