// ************************************************************************** //
//
//  Model-view-view-model framework for large GUI applications
//
//! @license   GNU General Public License v3 or higher (see COPYING)
//! @authors   see AUTHORS
//
// ************************************************************************** //

#ifndef MVVM_SIGNALS_MODELLISTENERBASE_H
#define MVVM_SIGNALS_MODELLISTENERBASE_H

#include <mvvm/core/export.h>
#include <mvvm/signals/callback_types.h>

namespace ModelView
{

class SessionModel;

//! Provides sets of methods to subscribe to various signals generated by SessionModel.
//! Automatically tracks the time of life of SessionModel. Unsubscribes from the model on
//! own destruction.

// FIXME introduce pure interface and share together with ModelMapper

class CORE_EXPORT ModelListenerBase
{
public:
    ModelListenerBase(SessionModel* model);
    virtual ~ModelListenerBase();

    void setOnDataChange(Callbacks::item_int_t f);
    void setOnItemInserted(Callbacks::item_tagrow_t f);
    void setOnItemRemoved(Callbacks::item_tagrow_t f);
    void setOnAboutToRemoveItem(Callbacks::item_tagrow_t f);
    void setOnModelAboutToBeReset(Callbacks::model_t f);
    void setOnModelReset(Callbacks::model_t f);

protected:
    SessionModel* m_model{nullptr};
};

} // namespace ModelView

#endif // MVVM_SIGNALS_MODELLISTENERBASE_H
