#include "google_test.h"
#include "toy_includes.h"

using namespace ModelView;

//! Testing various toy items generated by toy SampleModel.

class TestToyItem : public ::testing::Test
{
public:
    ~TestToyItem();
};

TestToyItem::~TestToyItem() = default;

//! Toy multilayer as produced bo toy SampleModel.

TEST_F(TestToyItem, multiLayer)
{
    ToyItems::SampleModel model;
    auto multiLayer = model.insertNewItem(ToyItems::Constants::MultiLayerType);

    EXPECT_FALSE(multiLayer->data(ItemDataRole::DATA).isValid());
    EXPECT_EQ(multiLayer->displayName(), ToyItems::Constants::MultiLayerType);
}
